-- Faz 3E-0b ana stok iskeleti, parça 9/10 (yemekler). scripts/gen_stock_seed.py üretir; elle düzenlemeyin.
insert into public.recipes (code, name, category_code, meals) values
  ('YM-0001', 'Mercimek Çorbası', 'corba', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0002', 'Ezogelin Çorbası', 'corba', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0003', 'Yeşil Mercimek Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0004', 'Düğün Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0005', 'Yayla Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0006', 'Pirinç Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0007', 'Sebze Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0008', 'Arap Aşı Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0009', 'Brokoli Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0010', 'Tavuk Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0011', 'Tarhana Çorbası', 'corba', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0012', 'Oba Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0013', 'Abant Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0014', 'Kafkas Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0015', 'Domates Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0016', 'Şehriye Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0017', 'Mantar Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0018', 'Kremalı Tavuk Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0019', 'Toyga Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0020', 'Lebeniye Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0021', 'Analı Kızlı Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0022', 'İşkembe Çorbası', 'corba', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0023', 'Kelle Paça Çorbası', 'corba', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0024', 'Beyran Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0025', 'Bulgur Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0026', 'Un Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0027', 'Havuç Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0028', 'Balkabağı Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0029', 'Pırasa Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0030', 'Patates Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0031', 'Kabak Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0032', 'Karnabahar Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0033', 'Mısır Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0034', 'Nohut Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0035', 'Kuru Fasulye Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0036', 'Ekşili Köfte Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0037', 'Sultan Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0038', 'Erişte Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0039', 'Kesme Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0040', 'Mahluta Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0041', 'Tutmaç Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0042', 'Balık Çorbası', 'corba', array['ogle','aksam']::text[]),
  ('YM-0043', 'Bahçıvan Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0044', 'Tas Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0045', 'Çiftlik Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0046', 'İslim Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0047', 'Orman Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0048', 'Beğendili Kebap', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0049', 'Hünkar Beğendi', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0050', 'Ankara Tava', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0051', 'Et Haşlama', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0052', 'Et Kızartma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0053', 'Et Döner', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0054', 'Et Sote', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0055', 'Rosto Et', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0056', 'Kuzu Kızartma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0057', 'Şehriyeli Güveç', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0058', 'Et Kavurma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0059', 'Etli Güveç', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0060', 'Kuzu Tandır', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0061', 'Kağıt Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0062', 'Tandır Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0063', 'Etli Nohut', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0064', 'Etli Kuru Fasulye', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0065', 'Etli Barbunya', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0066', 'Etli Yeşil Mercimek', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0067', 'İzmir Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0068', 'Dalyan Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0069', 'Kadınbudu Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0070', 'Sulu Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0071', 'Kuru Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0072', 'Rosto Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0073', 'Fırın Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0074', 'Terbiyeli Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0075', 'Izgara Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0076', 'Türlü Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0077', 'Patatesli Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0078', 'Hasanpaşa Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0079', 'Sebzeli Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0080', 'İnegöl Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0081', 'Kıymalı Karnabahar', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0082', 'Fırında Patates', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0083', 'Karnıyarık', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0084', 'Patlıcan Musakka', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0085', 'Etli Biber Dolma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0086', 'Etli Kabak Dolma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0087', 'Patates Oturtma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0088', 'Kıymalı Mantı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0089', 'Kıymalı Ispanak', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0090', 'Kıymalı Pırasa', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0091', 'Kıymalı Kabak', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0092', 'Kıymalı Patates', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0093', 'Kıymalı Bezelye', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0094', 'Patates Musakka', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0095', 'Kabak Musakka', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0096', 'Lahana Sarma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0097', 'Etli Yaprak Sarma', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0098', 'Etli Taze Fasulye', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0099', 'Etli Bezelye', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0100', 'Etli Bamya', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0101', 'Etli Karnabahar', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0102', 'Etli Türlü', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0103', 'Etli Kereviz', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0104', 'Etli Pırasa', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0105', 'Etli Enginar', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0106', 'Tavuk Haşlama', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0107', 'Fırın Tavuk', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0108', 'Tavuk Şinitzel', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0109', 'Tavuk Sote', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0110', 'Tavuk Külbastı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0111', 'Tavuk Topkapı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0112', 'Hindi Sote', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0113', 'Hindi Rosto', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0114', 'Tavuk Döner', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0115', 'Tavuk But Izgara', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0116', 'Tavuk Izgara', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0117', 'Tavuk Pirzola', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0118', 'Tavuk Kanat', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0119', 'Tavuk Güveç', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0120', 'Tavuklu Bezelye', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0121', 'Tavuk Fajita', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0122', 'Köri Soslu Tavuk', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0123', 'Kremalı Mantarlı Tavuk', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0124', 'Çıtır Tavuk', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0125', 'Tavuk Kebabı', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0126', 'Tavuk Tantuni', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0127', 'Piliç Baget', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0128', 'Çerkez Tavuğu', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0129', 'Fırın Levrek', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0130', 'Fırın Çipura', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0131', 'Alabalık Izgara', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0132', 'Hamsi Tava', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0133', 'Palamut Izgara', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0134', 'Somon Izgara', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0135', 'Mezgit Tava', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0136', 'Balık Buğulama', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0137', 'Balık Köfte', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0138', 'Hamsili Pilav', 'ana_yemek', array['ogle','aksam']::text[]),
  ('YM-0139', 'Kuru Fasulye', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0140', 'Nohut', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0141', 'Bezelye', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0142', 'Taze Fasulye', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0143', 'Türlü', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0144', 'Ispanak', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0145', 'Pırasa', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0146', 'Kabak Yemeği', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0147', 'Patates Yemeği', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0148', 'Karnabahar Yemeği', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0149', 'Bamya', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0150', 'Mantar Sote', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0151', 'Sebze Sote', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0152', 'Fırın Sebze', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0153', 'Mücver', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0154', 'Barbunya', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0155', 'Yeşil Mercimek', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0156', 'Sebzeli Nohut', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0157', 'Zeytinyağlı Pırasa', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0158', 'Zeytinyağlı Taze Fasulye', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0159', 'Zeytinyağlı Dolma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0160', 'Zeytinyağlı Sarma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0161', 'Zeytinyağlı Enginar', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0162', 'Zeytinyağlı Kereviz', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0163', 'Zeytinyağlı Barbunya', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0164', 'Zeytinyağlı Bamya', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0165', 'Zeytinyağlı Kabak', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0166', 'Zeytinyağlı Brokoli', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0167', 'Zeytinyağlı Karnabahar', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0168', 'İmam Bayıldı', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0169', 'Şakşuka', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0170', 'Barbunya Pilaki', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0171', 'Biber Kızartma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0172', 'Patlıcan Kızartma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0173', 'Patates Kızartması', 'sebze', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0174', 'Kabak Kızartma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0175', 'Karışık Kızartma', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0176', 'Patates Püresi', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0177', 'Haşlanmış Sebze', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0178', 'Söğüş Sebze', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0179', 'Közlenmiş Sebze', 'sebze', array['ogle','aksam']::text[]),
  ('YM-0180', 'Pirinç Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0181', 'Bulgur Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0182', 'İç Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0183', 'Gökçesu Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0184', 'Şehriyeli Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0185', 'Nohutlu Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0186', 'Sebzeli Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0187', 'Domatesli Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0188', 'Özbek Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0189', 'Perde Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0190', 'Etli Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0191', 'Tavuklu Pilav', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0192', 'Mercimekli Bulgur Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0193', 'Domatesli Bulgur Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0194', 'Şehriyeli Bulgur Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0195', 'Meyhane Pilavı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0196', 'Peynirli Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0197', 'Domates Soslu Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0198', 'Kıymalı Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0199', 'Fırın Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0200', 'Kremalı Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0201', 'Ton Balıklı Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0202', 'Sebzeli Makarna', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0203', 'Spagetti Bolonez', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0204', 'Erişte', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0205', 'Mantı', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0206', 'Kuskus', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0207', 'Lazanya', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0208', 'Su Böreği', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0209', 'Kol Böreği', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0210', 'Sigara Böreği', 'pilav_makarna', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0211', 'Ispanaklı Börek', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0212', 'Patatesli Börek', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0213', 'Kıymalı Börek', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0214', 'Peynirli Börek', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0215', 'Tepsi Böreği', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0216', 'Pide', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0217', 'Lahmacun', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0218', 'Gözleme', 'pilav_makarna', array['ogle','aksam']::text[]),
  ('YM-0219', 'Mevsim Salata', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0220', 'Çoban Salata', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0221', 'Patates Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0222', 'Kısır', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0223', 'Yoğurtlu Kereviz Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0224', 'Havuç Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0225', 'Brokoli Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0226', 'Karnabahar Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0227', 'Rus Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0228', 'Makarna Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0229', 'Ton Balıklı Salata', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0230', 'Gavurdağı Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0231', 'Piyaz', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0232', 'Yeşil Mercimek Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0233', 'Nohut Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0234', 'Beyaz Lahana Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0235', 'Kırmızı Lahana Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0236', 'Pancar Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0237', 'Semizotu Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0238', 'Roka Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0239', 'Göbek Salata', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0240', 'Tavuklu Salata', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0241', 'Bulgur Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0242', 'Cacık', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0243', 'Haydari', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0244', 'Humus', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0245', 'Acılı Ezme', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0246', 'Babagannuş', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0247', 'Patlıcan Salatası', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0248', 'Yoğurtlu Semizotu', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0249', 'Ispanak Tarator', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0250', 'Havuç Tarator', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0251', 'Atom', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0252', 'Turşu', 'salata_meze', array['ogle','aksam']::text[]),
  ('YM-0253', 'Yoğurt', 'salata_meze', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0254', 'Ayran', 'salata_meze', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0255', 'Sütlaç', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0256', 'Keşkül', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0257', 'Supangle', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0258', 'Muhallebi', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0259', 'Kazandibi', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0260', 'Tavuk Göğsü', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0261', 'Puding', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0262', 'Güllaç', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0263', 'Revani', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0264', 'Baklava', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0265', 'Kadayıf', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0266', 'Tulumba', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0267', 'Şekerpare', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0268', 'Şöbiyet', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0269', 'Un Helvası', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0270', 'İrmik Helvası', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0271', 'Yaz Helvası', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0272', 'Tahin Helva', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0273', 'Ekmek Kadayıfı', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0274', 'Kabak Tatlısı', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0275', 'Ayva Tatlısı', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0276', 'Aşure', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0277', 'Kek', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0278', 'Islak Kek', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0279', 'Browni', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0280', 'Kurabiye', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0281', 'Dondurma', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0282', 'Jöle', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0283', 'Meyve', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0284', 'Vişne Kompostosu', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0285', 'Ayva Kompostosu', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0286', 'Erik Kompostosu', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0287', 'Elma Kompostosu', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0288', 'Hoşaf', 'tatli', array['ogle','aksam']::text[]),
  ('YM-0289', 'Beyaz Peynir', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0290', 'Kaşar Peyniri', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0291', 'Üçgen Peynir', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0292', 'Siyah Zeytin', 'kahvalti', array['kahvalti']::text[])
on conflict do nothing;
