-- Faz 3E-0b ana stok iskeleti, parça 10/10 (yemekler). scripts/gen_stock_seed.py üretir; elle düzenlemeyin.
insert into public.recipes (code, name, category_code, meals) values
  ('YM-0293', 'Yeşil Zeytin', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0294', 'Haşlanmış Yumurta', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0295', 'Menemen', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0296', 'Omlet', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0297', 'Sucuklu Yumurta', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0298', 'Peynirli Omlet', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0299', 'Çılbır', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0300', 'Bal', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0301', 'Reçel', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0302', 'Tahin Pekmez', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0303', 'Pekmez', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0304', 'Fındık Ezmesi', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0305', 'Tereyağı', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0306', 'Kaymak', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0307', 'Domates Salatalık', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0308', 'Söğüş Domates', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0309', 'Poğaça', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0310', 'Simit', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0311', 'Açma', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0312', 'Kaşarlı Tost', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0313', 'Sosis Tava', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0314', 'Pişi', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0315', 'Yulaf Lapası', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0316', 'Sütlü Mısır Gevreği', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0317', 'Kahvaltı Tabağı', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0318', 'Kumanya', 'kahvalti', array['kahvalti']::text[]),
  ('YM-0319', 'Çay', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0320', 'Süt', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0321', 'Ihlamur', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0322', 'Türk Kahvesi', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0323', 'Meyve Suyu', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0324', 'Limonata', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0325', 'Şalgam', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0326', 'Su', 'icecek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0327', 'Ekmek', 'ekmek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0328', 'Roll Ekmek', 'ekmek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0329', 'Tam Buğday Ekmeği', 'ekmek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0330', 'Lavaş', 'ekmek', array['kahvalti','ogle','aksam']::text[]),
  ('YM-0331', 'Bazlama', 'ekmek', array['kahvalti','ogle','aksam']::text[])
on conflict do nothing;
