-- Faz 3E-0b ana stok iskeleti, parça 2/10 (stok_kartlari). scripts/gen_stock_seed.py üretir; elle düzenlemeyin.
insert into public.ingredients (code, name, category, stock_unit, vat_rate, allergens, notes) values
  ('BT-0029', 'Yulaf', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: tahil'),
  ('BT-0030', 'Mısır Unu', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: un'),
  ('BT-0031', 'Konserve Mısır', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('BT-0032', 'Kinoa', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: tahil'),
  ('BT-0033', 'Karabuğday', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: tahil'),
  ('BT-0034', 'Susam', 'bakliyat_tahil', 'kg', 1, array['susam']::text[], 'Alt kategori: tahil'),
  ('BT-0035', 'Çörek Otu', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('EU-0001', 'Un', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: un'),
  ('EU-0002', 'Tam Buğday Unu', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: un'),
  ('EU-0003', 'Pirinç Unu', 'ekmek_unlu', 'kg', 1, '{}'::text[], 'Alt kategori: un'),
  ('EU-0004', 'İrmik', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: un'),
  ('EU-0005', 'Nişasta', 'ekmek_unlu', 'kg', 1, '{}'::text[], 'Alt kategori: un'),
  ('EU-0006', 'Galeta Unu', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: un'),
  ('EU-0007', 'Ekmek', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0008', 'Roll Ekmek', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0009', 'Tam Buğday Ekmeği', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0010', 'Lavaş', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0011', 'Pide', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0012', 'Yufka', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0013', 'Baklava Yufkası', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('EU-0014', 'Simit', 'ekmek_unlu', 'adet', 1, array['gluten','susam']::text[], 'Alt kategori: ekmek'),
  ('EU-0015', 'Poğaça', 'ekmek_unlu', 'adet', 1, array['gluten','sut','yumurta']::text[], 'Alt kategori: ekmek'),
  ('EU-0016', 'Kuru Maya', 'ekmek_unlu', 'kg', 1, '{}'::text[], 'Alt kategori: yardimci'),
  ('EU-0017', 'Yaş Maya', 'ekmek_unlu', 'kg', 1, '{}'::text[], 'Alt kategori: yardimci'),
  ('EU-0018', 'Kabartma Tozu', 'ekmek_unlu', 'kg', 1, '{}'::text[], 'Alt kategori: yardimci'),
  ('EU-0019', 'Tel Kadayıf', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: tatli_hamur'),
  ('EU-0020', 'Ekmek Kadayıfı', 'ekmek_unlu', 'adet', 1, array['gluten']::text[], 'Alt kategori: tatli_hamur'),
  ('EU-0021', 'Milföy', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: tatli_hamur'),
  ('EU-0022', 'Kraker', 'ekmek_unlu', 'kg', 1, array['gluten']::text[], 'Alt kategori: ekmek'),
  ('YG-0001', 'Ayçiçek Yağı', 'yag', 'lt', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0002', 'Kızartma Yağı', 'yag', 'lt', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0003', 'Sızma Zeytinyağı', 'yag', 'lt', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0004', 'Zeytinyağı', 'yag', 'lt', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0005', 'Mısırözü Yağı', 'yag', 'lt', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0006', 'Fındık Yağı', 'yag', 'lt', 1, array['sert_kabuklu']::text[], 'Alt kategori: yag'),
  ('YG-0007', 'Margarin', 'yag', 'kg', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0008', 'Teneke Margarin', 'yag', 'kg', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0009', 'Mutfak Yağı', 'yag', 'kg', 1, '{}'::text[], 'Alt kategori: yag'),
  ('YG-0010', 'Sade Yağ', 'yag', 'kg', 1, array['sut']::text[], 'Alt kategori: yag'),
  ('YG-0011', 'Susam Yağı', 'yag', 'lt', 1, array['susam']::text[], 'Alt kategori: yag'),
  ('BS-0001', 'Tuz', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: tuz'),
  ('BS-0002', 'Kaya Tuzu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: tuz'),
  ('BS-0003', 'Deniz Tuzu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: tuz'),
  ('BS-0004', 'Karabiber', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0005', 'Tane Karabiber', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0006', 'Toz Biber', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0007', 'Pul Biber', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0008', 'İsot', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0009', 'Acı Toz Biber', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0010', 'Kimyon', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0011', 'Kekik', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0012', 'Kuru Nane', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0013', 'Tarçın', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0014', 'Yenibahar', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0015', 'Sumak', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0016', 'Zerdeçal', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0017', 'Köri', 'baharat_sos', 'kg', 1, array['hardal']::text[], 'Alt kategori: baharat'),
  ('BS-0018', 'Defne Yaprağı', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0019', 'Karanfil', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0020', 'Muskat', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0021', 'Toz Zencefil', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0022', 'Sarımsak Tozu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0023', 'Soğan Tozu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0024', 'Köfte Baharatı', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0025', 'Tavuk Baharatı', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0026', 'Et Baharatı', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0027', 'Balık Baharatı', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0028', 'Çemen', 'baharat_sos', 'kg', 1, array['hardal']::text[], 'Alt kategori: baharat'),
  ('BS-0029', 'Anason', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0030', 'Rezene', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0031', 'Kişniş', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0032', 'Mahlep', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0033', 'Safran', 'baharat_sos', 'g', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0034', 'Vanilya', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('BS-0035', 'Kuru Fesleğen', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0036', 'Kuru Dereotu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0037', 'Kuru Biberiye', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat'),
  ('BS-0038', 'Limon Tuzu', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: baharat; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('BS-0039', 'Karbonat', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: yardimci; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('BS-0040', 'Hardal Tohumu', 'baharat_sos', 'kg', 1, array['hardal']::text[], 'Alt kategori: baharat'),
  ('BS-0041', 'Tavuk Bulyon', 'baharat_sos', 'kg', 1, array['kereviz','gluten']::text[], 'Alt kategori: bulyon'),
  ('BS-0042', 'Et Bulyon', 'baharat_sos', 'kg', 1, array['kereviz','gluten']::text[], 'Alt kategori: bulyon'),
  ('BS-0043', 'Sebze Bulyon', 'baharat_sos', 'kg', 1, array['kereviz']::text[], 'Alt kategori: bulyon'),
  ('BS-0044', 'Domates Salçası', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: salca'),
  ('BS-0045', 'Biber Salçası', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: salca'),
  ('BS-0046', 'Ketçap', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: sos'),
  ('BS-0047', 'Mayonez', 'baharat_sos', 'kg', 1, array['yumurta','hardal']::text[], 'Alt kategori: sos'),
  ('BS-0048', 'Hardal', 'baharat_sos', 'kg', 1, array['hardal']::text[], 'Alt kategori: sos'),
  ('BS-0049', 'Barbekü Sos', 'baharat_sos', 'kg', 1, array['hardal']::text[], 'Alt kategori: sos'),
  ('BS-0050', 'Acı Sos', 'baharat_sos', 'lt', 1, '{}'::text[], 'Alt kategori: sos'),
  ('BS-0051', 'Soya Sosu', 'baharat_sos', 'lt', 1, array['soya','gluten']::text[], 'Alt kategori: sos'),
  ('BS-0052', 'Nar Ekşisi', 'baharat_sos', 'lt', 1, '{}'::text[], 'Alt kategori: sos'),
  ('BS-0053', 'Limon Sosu', 'baharat_sos', 'lt', 1, '{}'::text[], 'Alt kategori: sos'),
  ('BS-0054', 'Üzüm Sirkesi', 'baharat_sos', 'lt', 1, array['sulfit']::text[], 'Alt kategori: sos'),
  ('BS-0055', 'Elma Sirkesi', 'baharat_sos', 'lt', 1, '{}'::text[], 'Alt kategori: sos'),
  ('BS-0056', 'Tahin', 'baharat_sos', 'kg', 1, array['susam']::text[], 'Alt kategori: sos'),
  ('BS-0057', 'Pekmez', 'baharat_sos', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('BS-0058', 'Tahin Pekmez', 'baharat_sos', 'kg', 1, array['susam']::text[], 'Alt kategori: tatli_yardimci'),
  ('BS-0059', 'Beşamel Sos', 'baharat_sos', 'kg', 1, array['sut','gluten']::text[], 'Alt kategori: sos'),
  ('BS-0060', 'Pesto Sos', 'baharat_sos', 'kg', 1, array['sut','sert_kabuklu']::text[], 'Alt kategori: sos'),
  ('BS-0061', 'Ranch Sos', 'baharat_sos', 'kg', 1, array['sut','yumurta']::text[], 'Alt kategori: sos'),
  ('BS-0062', 'Salata Sosu', 'baharat_sos', 'lt', 1, array['hardal']::text[], 'Alt kategori: sos'),
  ('BS-0063', 'Ketçap Saşe', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0064', 'Mayonez Saşe', 'baharat_sos', 'adet', 1, array['yumurta','hardal']::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0065', 'Hardal Saşe', 'baharat_sos', 'adet', 1, array['hardal']::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0066', 'Tuz Saşe', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0067', 'Karabiber Saşe', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0068', 'Şeker Saşe', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0069', 'Limon Sosu Saşe', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0070', 'Zeytinyağı Porsiyon', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: sos_porsiyon'),
  ('BS-0071', 'Bal Porsiyon', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: kahvalti'),
  ('BS-0072', 'Reçel Porsiyon', 'baharat_sos', 'adet', 1, '{}'::text[], 'Alt kategori: kahvalti'),
  ('BS-0073', 'Porsiyon Çikolata Krema', 'baharat_sos', 'adet', 1, array['sut','sert_kabuklu','soya']::text[], 'Alt kategori: kahvalti'),
  ('KG-0001', 'Kornişon Turşu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tursu'),
  ('KG-0002', 'Biber Turşusu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tursu'),
  ('KG-0003', 'Karışık Turşu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tursu'),
  ('KG-0004', 'Lahana Turşusu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tursu'),
  ('KG-0005', 'Yeşil Zeytin', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: zeytin'),
  ('KG-0006', 'Siyah Zeytin', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: zeytin'),
  ('KG-0007', 'Zeytin Porsiyon', 'kuru_gida', 'adet', 1, '{}'::text[], 'Alt kategori: zeytin'),
  ('KG-0008', 'Konserve Barbunya Pilaki', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0009', 'Konserve Nohut', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0010', 'Konserve Bezelye', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0011', 'Konserve Mantar', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0012', 'Domates Püresi', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0013', 'Közlenmiş Biber', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0014', 'Közlenmiş Patlıcan', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0015', 'Yaprak Sarma', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0016', 'Salamura Asma Yaprağı', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0017', 'Kapari', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: konserve'),
  ('KG-0018', 'Acılı Ezme', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: konserve'),
  ('KG-0019', 'Donuk Bezelye', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0020', 'Donuk Garnitür', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0021', 'Donuk Fasulye', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0022', 'Donuk Ispanak', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0023', 'Donuk Brokoli', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0024', 'Donuk Karnabahar', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0025', 'Donuk Bamya', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0026', 'Donuk Enginar', 'kuru_gida', 'adet', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0027', 'Donuk Mantar', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0028', 'Donuk Mısır', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0029', 'Donuk Patates', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0030', 'Donuk Sebze Karışımı', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0031', 'Donuk Orman Meyvesi', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: dondurulmus'),
  ('KG-0032', 'Sigara Böreği', 'kuru_gida', 'kg', 1, array['gluten','sut']::text[], 'Alt kategori: dondurulmus'),
  ('KG-0033', 'İçli Köfte', 'kuru_gida', 'adet', 1, array['gluten']::text[], 'Alt kategori: dondurulmus'),
  ('KG-0034', 'Mücver Harcı', 'kuru_gida', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: dondurulmus'),
  ('IC-0001', 'Pet Su', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: su'),
  ('IC-0002', 'Bardak Su', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: su'),
  ('IC-0003', 'Büyük Pet Su', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: su'),
  ('IC-0004', 'Damacana Su', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: su'),
  ('IC-0005', 'Maden Suyu', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: su'),
  ('IC-0006', 'Meyveli Soda', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: gazli; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('IC-0007', 'Meyve Suyu', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: meyve_suyu'),
  ('IC-0008', 'Meyve Nektarı', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: meyve_suyu'),
  ('IC-0009', 'Litrelik Meyve Suyu', 'icecek', 'lt', 1, '{}'::text[], 'Alt kategori: meyve_suyu'),
  ('IC-0010', 'Kola', 'icecek', 'adet', 10, '{}'::text[], 'Alt kategori: gazli; KDV: ÖTV (III) listesindeki gazlı içecek varsayımı; Karar md.1/(3) → %10'),
  ('IC-0011', 'Pet Kola', 'icecek', 'adet', 10, '{}'::text[], 'Alt kategori: gazli; KDV: ÖTV (III) listesindeki gazlı içecek varsayımı; Karar md.1/(3) → %10'),
  ('IC-0012', 'Gazoz', 'icecek', 'adet', 10, '{}'::text[], 'Alt kategori: gazli; KDV: ÖTV (III) listesindeki gazlı içecek varsayımı; Karar md.1/(3) → %10'),
  ('IC-0013', 'Soğuk Çay', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: gazli; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('IC-0014', 'Şalgam Suyu', 'icecek', 'lt', 1, '{}'::text[], 'Alt kategori: icecek_diger; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('IC-0015', 'Limonata', 'icecek', 'lt', 1, '{}'::text[], 'Alt kategori: icecek_diger; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('IC-0016', 'Çay', 'icecek', 'kg', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0017', 'Bardak Poşet Çay', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0018', 'Demlik Poşet Çay', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0019', 'Bitki Çayı', 'icecek', 'adet', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0020', 'Türk Kahvesi', 'icecek', 'kg', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0021', 'Hazır Kahve', 'icecek', 'kg', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0022', 'Filtre Kahve', 'icecek', 'kg', 1, '{}'::text[], 'Alt kategori: cay_kahve'),
  ('IC-0023', 'Kahve Kreması', 'icecek', 'kg', 1, array['sut']::text[], 'Alt kategori: cay_kahve'),
  ('IC-0024', 'Sıcak Çikolata', 'icecek', 'kg', 1, array['sut']::text[], 'Alt kategori: cay_kahve'),
  ('KG-0035', 'Şeker', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: seker'),
  ('KG-0036', 'Küp Şeker', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: seker'),
  ('KG-0037', 'Pudra Şekeri', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: seker'),
  ('KG-0038', 'Esmer Şeker', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: seker'),
  ('KG-0039', 'Glikoz Şurubu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: seker'),
  ('KG-0040', 'Bal', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kahvalti'),
  ('KG-0041', 'Reçel', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kahvalti'),
  ('KG-0042', 'Fındık Kreması', 'kuru_gida', 'kg', 1, array['sut','sert_kabuklu','soya']::text[], 'Alt kategori: kahvalti'),
  ('KG-0043', 'Tahin Helva', 'kuru_gida', 'kg', 1, array['susam']::text[], 'Alt kategori: tatli'),
  ('KG-0044', 'Baklava', 'kuru_gida', 'kg', 1, array['gluten','sert_kabuklu','sut']::text[], 'Alt kategori: tatli'),
  ('KG-0045', 'Tulumba', 'kuru_gida', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: tatli'),
  ('KG-0046', 'Şöbiyet', 'kuru_gida', 'kg', 1, array['gluten','sert_kabuklu','sut']::text[], 'Alt kategori: tatli'),
  ('KG-0047', 'Kakao', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0048', 'Bitter Çikolata', 'kuru_gida', 'kg', 1, array['sut','soya']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0049', 'Sütlü Çikolata', 'kuru_gida', 'kg', 1, array['sut','soya']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0050', 'Damla Çikolata', 'kuru_gida', 'kg', 1, array['sut','soya']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0051', 'Puding', 'kuru_gida', 'kg', 1, array['sut']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0052', 'Muhallebi Tozu', 'kuru_gida', 'kg', 1, array['sut']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0053', 'Jöle Tozu', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0054', 'Jelatin', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('KG-0055', 'Keşkül Karışımı', 'kuru_gida', 'kg', 1, array['sut','sert_kabuklu']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0056', 'Revani Karışımı', 'kuru_gida', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0057', 'Kek Karışımı', 'kuru_gida', 'kg', 1, array['gluten','yumurta','sut']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0058', 'Damla Sakızı', 'kuru_gida', 'g', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0059', 'Gül Suyu', 'kuru_gida', 'lt', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0060', 'Hindistan Cevizi Rendesi', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0061', 'Gıda Boyası', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli_yardimci; KDV teyit edilmeli; KDV: GTİP/ÖTV durumuna göre muhasebe teyidi gerekli'),
  ('KG-0062', 'Bisküvi', 'kuru_gida', 'kg', 1, array['gluten','sut']::text[], 'Alt kategori: tatli_yardimci'),
  ('KG-0063', 'Lokum', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: tatli'),
  ('KG-0064', 'Paket Kek', 'kuru_gida', 'adet', 1, array['gluten','yumurta','sut']::text[], 'Alt kategori: tatli'),
  ('KG-0065', 'Paket Bisküvi', 'kuru_gida', 'adet', 1, array['gluten','sut']::text[], 'Alt kategori: tatli'),
  ('KG-0066', 'Ceviz İçi', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0067', 'Fındık İçi', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0068', 'Badem İçi', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0069', 'Antep Fıstığı İçi', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0070', 'Çam Fıstığı', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuruyemis'),
  ('KG-0071', 'Yer Fıstığı', 'kuru_gida', 'kg', 1, array['yer_fistigi']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0072', 'Kaju', 'kuru_gida', 'kg', 1, array['sert_kabuklu']::text[], 'Alt kategori: kuruyemis'),
  ('KG-0073', 'Leblebi', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuruyemis'),
  ('KG-0074', 'Ay Çekirdeği', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuruyemis'),
  ('KG-0075', 'Kuru Üzüm', 'kuru_gida', 'kg', 1, array['sulfit']::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0076', 'Kuş Üzümü', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0077', 'Kuru Kayısı', 'kuru_gida', 'kg', 1, array['sulfit']::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0078', 'Kuru İncir', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0079', 'Kuru Erik', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0080', 'Hurma', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0081', 'Kuru Dut', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve')
on conflict do nothing;
