-- Faz 3E-0b ana stok iskeleti, parça 1/10 (stok_kartlari). scripts/gen_stock_seed.py üretir; elle düzenlemeyin.
insert into public.ingredients (code, name, category, stock_unit, vat_rate, allergens, notes) values
  ('SM-0001', 'Domates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0002', 'Cherry Domates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0003', 'Salçalık Domates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0004', 'Salatalık', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0005', 'Kornişon Salatalık', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0006', 'Patlıcan', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0007', 'Dolmalık Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0008', 'Sivri Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0009', 'Acı Sivri Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0010', 'Çarliston Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0011', 'Kapya Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0012', 'Köy Biberi', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0013', 'Şili Biber', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0014', 'Soğan', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0015', 'Kırmızı Soğan', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0016', 'Taze Soğan', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0017', 'Sarımsak', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0018', 'Soyulmuş Sarımsak', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0019', 'Patates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0020', 'Kızartmalık Patates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0021', 'Havuç', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0022', 'Taze Kabak', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0023', 'Bal Kabağı', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0024', 'Taze Fasulye', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0025', 'Taze Barbunya', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0026', 'Börülce', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0027', 'Bamya', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0028', 'Taze Bakla', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0029', 'Bezelye', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0030', 'Enginar', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0031', 'Ispanak', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0032', 'Pazı', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0033', 'Semizotu', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0034', 'Kuzukulağı', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0035', 'Pırasa', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0036', 'Karnabahar', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0037', 'Brokoli', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0038', 'Beyaz Lahana', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0039', 'Kırmızı Lahana', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0040', 'Kara Lahana', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0041', 'Kereviz', 'sebze_meyve', 'kg', 1, array['kereviz']::text[], 'Alt kategori: sebze'),
  ('SM-0042', 'Sap Kereviz', 'sebze_meyve', 'kg', 1, array['kereviz']::text[], 'Alt kategori: sebze'),
  ('SM-0043', 'Pancar', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0044', 'Kırmızı Turp', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0045', 'Siyah Turp', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0046', 'Mantar', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0047', 'İstiridye Mantar', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0048', 'Marul', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0049', 'Aysberg Marul', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0050', 'Kıvırcık Marul', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0051', 'Lollo Rosso', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0052', 'Roka', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0053', 'Tere', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0054', 'Maydanoz', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0055', 'Dereotu', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0056', 'Taze Nane', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0057', 'Reyhan', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0058', 'Taze Kekik', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0059', 'Taze Biberiye', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0060', 'Deniz Börülcesi', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0061', 'Acur', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0062', 'Zencefil', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0063', 'Taze Mısır', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0064', 'Yer Elması', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0065', 'Asma Yaprağı', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0066', 'Tatlı Patates', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: sebze'),
  ('SM-0067', 'Elma', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0068', 'Armut', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0069', 'Portakal', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0070', 'Mandalina', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0071', 'Limon', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0072', 'Greyfurt', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0073', 'Muz', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0074', 'Üzüm', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0075', 'Karpuz', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0076', 'Kavun', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0077', 'Şeftali', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0078', 'Nektarin', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0079', 'Kayısı', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0080', 'Erik', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0081', 'Kiraz', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0082', 'Vişne', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0083', 'Çilek', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0084', 'İncir', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0085', 'Nar', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0086', 'Ayva', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0087', 'Kivi', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0088', 'Ananas', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0089', 'Avokado', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0090', 'Mango', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0091', 'Hindistan Cevizi', 'sebze_meyve', 'adet', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0092', 'Taze Hurma', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0093', 'Trabzon Hurması', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0094', 'Böğürtlen', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0095', 'Yaban Mersini', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('SM-0096', 'Muşmula', 'sebze_meyve', 'kg', 1, '{}'::text[], 'Alt kategori: meyve'),
  ('ET-0001', 'Kıyma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0002', 'Yağsız Kıyma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0003', 'Köftelik Kıyma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0004', 'Dana Kuşbaşı', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0005', 'Dana But', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0006', 'Dana Kol', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0007', 'Dana Döş', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0008', 'Dana Antrikot', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0009', 'Dana Bonfile', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0010', 'Dana Kontrfile', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0011', 'Dana Kemikli Et', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0012', 'Dana İncik', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0013', 'Dana Kaburga', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0014', 'Dana Ciğer', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: sakatat'),
  ('ET-0015', 'Dana İşkembe', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: sakatat'),
  ('ET-0016', 'Dana Dil', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: sakatat'),
  ('ET-0017', 'Paça', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: sakatat'),
  ('ET-0018', 'Kuzu Kuşbaşı', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0019', 'Kuzu But', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0020', 'Kuzu İncik', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0021', 'Kuzu Pirzola', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0022', 'Kuzu Kol', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0023', 'Koyun Eti', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: kirmizi_et'),
  ('ET-0024', 'Kuzu Ciğer', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: sakatat'),
  ('ET-0025', 'Et Döner', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0026', 'Hazır Köfte', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0027', 'Kavurma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0028', 'Sucuk', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0029', 'Salam', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0030', 'Sosis', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0031', 'Pastırma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0032', 'Hindi Füme', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: islenmis_et'),
  ('ET-0033', 'Bütün Tavuk', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0034', 'Tavuk Göğüs', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0035', 'Kemikli Tavuk Göğüs', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0036', 'Tavuk But', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0037', 'Tavuk Pirzola', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0038', 'Tavuk Baget', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0039', 'Tavuk İncik', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0040', 'Tavuk Kanat', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0041', 'Tavuk Ciğer', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0042', 'Tavuk Taşlık', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0043', 'Tavuk Kuşbaşı', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0044', 'Tavuk Döner', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0045', 'Tavuk Şinitzel', 'et_tavuk', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: beyaz_et'),
  ('ET-0046', 'Tavuk Nugget', 'et_tavuk', 'kg', 1, array['gluten']::text[], 'Alt kategori: beyaz_et'),
  ('ET-0047', 'Tavuk Kıyma', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0048', 'Hindi Göğüs', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0049', 'Hindi But', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('ET-0050', 'Tavuk Kemiği', 'et_tavuk', 'kg', 1, '{}'::text[], 'Alt kategori: beyaz_et'),
  ('BL-0001', 'Hamsi', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0002', 'İstavrit', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0003', 'Sardalya', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0004', 'Palamut', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0005', 'Uskumru', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0006', 'Levrek', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0007', 'Çipura', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0008', 'Alabalık', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0009', 'Somon', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0010', 'Mezgit', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0011', 'Kefal', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0012', 'Lüfer', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0013', 'Barbun', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0014', 'Kolyoz', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0015', 'Bakalyaro', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0016', 'Sazan', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0017', 'Kalkan', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0018', 'Dil Balığı', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0019', 'Mercan', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0020', 'Kılıç Balığı', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_taze'),
  ('BL-0021', 'Pangasius', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_donuk'),
  ('BL-0022', 'Mezgit Fileto', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_donuk'),
  ('BL-0023', 'Levrek Fileto', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_donuk'),
  ('BL-0024', 'Somon Fileto', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_donuk'),
  ('BL-0025', 'Balık Kroket', 'balik', 'kg', 1, array['balik','gluten']::text[], 'Alt kategori: balik_donuk'),
  ('BL-0026', 'Karides', 'balik', 'kg', 1, array['kabuklu_deniz']::text[], 'Alt kategori: deniz_urunu'),
  ('BL-0027', 'Kalamar', 'balik', 'kg', 1, array['yumusakca']::text[], 'Alt kategori: deniz_urunu'),
  ('BL-0028', 'Ahtapot', 'balik', 'kg', 1, array['yumusakca']::text[], 'Alt kategori: deniz_urunu'),
  ('BL-0029', 'Midye', 'balik', 'kg', 1, array['yumusakca']::text[], 'Alt kategori: deniz_urunu'),
  ('BL-0030', 'Ton Balığı', 'balik', 'kg', 1, array['balik']::text[], 'Alt kategori: balik_konserve'),
  ('SU-0001', 'Süt', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: sut'),
  ('SU-0002', 'Uzun Ömürlü Süt', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: sut'),
  ('SU-0003', 'Açık Süt', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: sut'),
  ('SU-0004', 'Yoğurt', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: yogurt'),
  ('SU-0005', 'Süzme Yoğurt', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: yogurt'),
  ('SU-0006', 'Kase Yoğurt', 'sut_urunleri', 'adet', 1, array['sut']::text[], 'Alt kategori: yogurt'),
  ('SU-0007', 'Ayran', 'sut_urunleri', 'adet', 1, array['sut']::text[], 'Alt kategori: ayran'),
  ('SU-0008', 'Dökme Ayran', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: ayran'),
  ('SU-0009', 'Beyaz Peynir', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0010', 'Kaşar Peyniri', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0011', 'Rendelenmiş Kaşar', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0012', 'Tulum Peyniri', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0013', 'Lor Peyniri', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0014', 'Çökelek', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0015', 'Krem Peynir', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0016', 'Üçgen Peynir', 'sut_urunleri', 'adet', 1, array['sut']::text[], 'Alt kategori: peynir'),
  ('SU-0017', 'Tereyağı', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: tereyagi'),
  ('SU-0018', 'Porsiyon Tereyağı', 'sut_urunleri', 'adet', 1, array['sut']::text[], 'Alt kategori: tereyagi'),
  ('SU-0019', 'Sıvı Krema', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: krema'),
  ('SU-0020', 'Krem Şanti', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: krema'),
  ('SU-0021', 'Kaymak', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: krema'),
  ('SU-0022', 'Süt Tozu', 'sut_urunleri', 'kg', 1, array['sut']::text[], 'Alt kategori: sut'),
  ('SU-0023', 'Kefir', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: sut'),
  ('SU-0024', 'Dondurma', 'sut_urunleri', 'lt', 1, array['sut']::text[], 'Alt kategori: tatli_sut'),
  ('SU-0025', 'Hazır Sütlaç', 'sut_urunleri', 'adet', 1, array['sut']::text[], 'Alt kategori: tatli_sut'),
  ('SU-0026', 'Yumurta', 'sut_urunleri', 'adet', 1, array['yumurta']::text[], 'Alt kategori: yumurta'),
  ('SU-0027', 'Sıvı Yumurta', 'sut_urunleri', 'kg', 1, array['yumurta']::text[], 'Alt kategori: yumurta'),
  ('SU-0028', 'Haşlanmış Yumurta', 'sut_urunleri', 'adet', 1, array['yumurta']::text[], 'Alt kategori: yumurta'),
  ('SU-0029', 'Bıldırcın Yumurtası', 'sut_urunleri', 'adet', 1, array['yumurta']::text[], 'Alt kategori: yumurta'),
  ('BT-0001', 'Baldo Pirinç', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: pirinc'),
  ('BT-0002', 'Osmancık Pirinç', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: pirinc'),
  ('BT-0003', 'Kırık Pirinç', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: pirinc'),
  ('BT-0004', 'Basmati Pirinç', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: pirinc'),
  ('BT-0005', 'Pilavlık Bulgur', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: bulgur'),
  ('BT-0006', 'Köftelik Bulgur', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: bulgur'),
  ('BT-0007', 'Başbaşı Bulgur', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: bulgur'),
  ('BT-0008', 'Firik Bulgur', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: bulgur'),
  ('BT-0009', 'Kırmızı Mercimek', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0010', 'Yeşil Mercimek', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0011', 'Kuru Fasulye', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0012', 'Barbunya', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0013', 'Nohut', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0014', 'Kuru Börülce', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0015', 'Kuru Bakla', 'bakliyat_tahil', 'kg', 1, '{}'::text[], 'Alt kategori: bakliyat'),
  ('BT-0016', 'Aşurelik Buğday', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: tahil'),
  ('BT-0017', 'Buğday', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: tahil'),
  ('BT-0018', 'Arpa Şehriye', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0019', 'Tel Şehriye', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0020', 'Spagetti', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0021', 'Burgu Makarna', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0022', 'Kalem Makarna', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0023', 'Fiyonk Makarna', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0024', 'Boru Makarna', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0025', 'Lazanya Makarna', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna'),
  ('BT-0026', 'Erişte', 'bakliyat_tahil', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: makarna'),
  ('BT-0027', 'Mantı', 'bakliyat_tahil', 'kg', 1, array['gluten','yumurta']::text[], 'Alt kategori: makarna'),
  ('BT-0028', 'Kuskus', 'bakliyat_tahil', 'kg', 1, array['gluten']::text[], 'Alt kategori: makarna')
on conflict do nothing;
