-- Faz 3E-0b ana stok iskeleti, parça 3/10 (stok_kartlari). scripts/gen_stock_seed.py üretir; elle düzenlemeyin.
insert into public.ingredients (code, name, category, stock_unit, vat_rate, allergens, notes) values
  ('KG-0082', 'Kuru Domates', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0083', 'Kuru Dolmalık', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuru_meyve'),
  ('KG-0084', 'Kestane', 'kuru_gida', 'kg', 1, '{}'::text[], 'Alt kategori: kuruyemis'),
  ('KG-0085', 'Hoşaflık Meyve', 'kuru_gida', 'kg', 1, array['sulfit']::text[], 'Alt kategori: kuru_meyve'),
  ('TS-0001', 'Bulaşık Makinesi Deterjanı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0002', 'Parlatıcı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0003', 'Bulaşık Tableti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0004', 'Bulaşık Deterjanı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0005', 'Yağ Çözücü', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0006', 'Kireç Çözücü', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0007', 'Yüzey Temizleyici', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0008', 'Yüzey Dezenfektanı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0009', 'Çamaşır Suyu', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0010', 'Sebze Dezenfektanı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0011', 'Klor Tablet', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0012', 'Cam Temizleyici', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0013', 'Tuz Ruhu', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0014', 'Arap Sabunu', 'temizlik_sarf', 'kg', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0015', 'Çamaşır Deterjanı', 'temizlik_sarf', 'kg', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0016', 'Çamaşır Yumuşatıcı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0017', 'Çelik Temizleyici', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0018', 'Tuvalet Temizleyici', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0019', 'Oda Kokusu', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0020', 'Böcek İlacı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0021', 'Bulaşık Süngeri', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0022', 'Bulaşık Teli', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0023', 'Mikrofiber Bez', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0024', 'Yer Bezi', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0025', 'Mop Başlığı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0026', 'Çekpas', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0027', 'Süpürge', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0028', 'Jumbo Çöp Poşeti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0029', 'Orta Çöp Poşeti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0030', 'Küçük Çöp Poşeti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: temizlik'),
  ('TS-0031', 'Sıvı Sabun', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0032', 'El Dezenfektanı', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0033', 'Kolonya', 'temizlik_sarf', 'lt', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0034', 'Nitril Eldiven', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0035', 'Vinil Eldiven', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0036', 'Poşet Eldiven', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0037', 'Bulaşık Eldiveni', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0038', 'Bone', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0039', 'Maske', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0040', 'Galoş', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0041', 'Önlük', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0042', 'Kolluk', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: hijyen'),
  ('TS-0043', 'Tuvalet Kağıdı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0044', 'Kağıt Havlu', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0045', 'İçten Çekmeli Havlu', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0046', 'Z Katlı Havlu', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0047', 'Islak Mendil', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0048', 'Peçete', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0049', 'Dispenser Peçete', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0050', 'Garson Peçete', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kagit'),
  ('TS-0051', '3 Bölmeli Kap', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0052', '3 Bölmeli Köpük Kap', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0053', '2 Bölmeli Kap', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0054', 'Tek Bölmeli Kap', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0055', '3 Bölmeli Kap Kapağı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0056', 'Çorba Kasesi', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0057', 'Büyük Çorba Kasesi', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0058', 'Salata Kasesi', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0059', 'Sos Kabı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0060', 'Alüminyum Kap', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0061', 'Streç Film', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0062', 'Alüminyum Folyo', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0063', 'Pişirme Kağıdı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0064', 'Vakum Poşeti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0065', 'Kilitli Poşet', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0066', 'Ekmek Poşeti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0067', 'Atlet Poşet', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0068', 'Kağıt Çanta', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0069', 'Karton Koli', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0070', 'Etiket', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0071', 'Koli Bandı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: ambalaj'),
  ('TS-0072', 'Küvet GN 1/1', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0073', 'Küvet GN 1/1 Derin', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0074', 'Küvet GN 1/1 Çok Derin', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0075', 'Küvet GN 1/2', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0076', 'Küvet GN 1/2 Derin', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0077', 'Küvet GN 1/3', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0078', 'Küvet GN 1/4', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0079', 'Küvet Kapağı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0080', 'Alüminyum Küvet', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0081', 'Termobox', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0082', 'Servis Tepsisi', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: kuvet'),
  ('TS-0083', 'Çatal Kaşık Seti', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0084', 'Plastik Çatal', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0085', 'Plastik Kaşık', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0086', 'Plastik Bıçak', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0087', 'Ahşap Çatal Kaşık', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0088', 'Karton Bardak', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0089', 'Plastik Bardak', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0090', 'Bardak Kapağı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0091', 'Pipet', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0092', 'Karıştırıcı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0093', 'Kürdan', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0094', 'Köpük Tabak', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0095', 'Karton Tabak', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0096', 'Masa Örtüsü', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: servis_seti'),
  ('TS-0097', 'Kesme Tahtası', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: mutfak_sarf'),
  ('TS-0098', 'Termometre', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: mutfak_sarf'),
  ('TS-0099', 'Numune Kabı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: mutfak_sarf'),
  ('TS-0100', 'Sinek Kağıdı', 'temizlik_sarf', 'adet', 20, '{}'::text[], 'Alt kategori: mutfak_sarf'),
  ('DG-0001', 'Sanayi Tüpü', 'diger', 'adet', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0002', 'Mutfak Tüpü', 'diger', 'adet', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0003', 'Dökme LPG', 'diger', 'kg', 10, '{}'::text[], 'Alt kategori: enerji; KDV: (II) sayılı liste 31. sıra (LPG, otogaz hariç)'),
  ('DG-0004', 'Motorin', 'diger', 'lt', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0005', 'Benzin', 'diger', 'lt', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0006', 'Mangal Kömürü', 'diger', 'kg', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0007', 'Jel Yakıt', 'diger', 'adet', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0008', 'Çakmak', 'diger', 'adet', 20, '{}'::text[], 'Alt kategori: enerji'),
  ('DG-0009', 'AdBlue', 'diger', 'lt', 20, '{}'::text[], 'Alt kategori: enerji')
on conflict do nothing;
